// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PantryApplication.Data;

#nullable disable

namespace PantryApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241103171218_addItemToDb")]
    partial class addItemToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PantryApplication.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PantryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PantryId");

                    b.ToTable("Item");

                    b.HasDiscriminator<string>("ItemType").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PantryApplication.Models.Pantry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pantry");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("PantryApplication.Models.NonPerishableItem", b =>
                {
                    b.HasBaseType("PantryApplication.Models.Item");

                    b.Property<bool>("IsSealed")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("NonPerishable");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Brand = "Buschs",
                            Category = "Canned Goods",
                            DateAdded = new DateTime(2024, 11, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            ExpirationDate = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Location = "Pantry",
                            Name = "Baked Beans",
                            PantryId = 1,
                            Quantity = 3m,
                            Unit = "Cans",
                            IsSealed = true
                        });
                });

            modelBuilder.Entity("PantryApplication.Models.PerishableItem", b =>
                {
                    b.HasBaseType("PantryApplication.Models.Item");

                    b.Property<bool>("RequiresFreezing")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresRefrigeration")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Perishable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Fairlife",
                            Category = "Dairy",
                            DateAdded = new DateTime(2024, 11, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            ExpirationDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Location = "Fridge",
                            Name = "Milk",
                            PantryId = 1,
                            Quantity = 2m,
                            Unit = "Liters",
                            RequiresFreezing = false,
                            RequiresRefrigeration = true
                        });
                });

            modelBuilder.Entity("PantryApplication.Models.Item", b =>
                {
                    b.HasOne("PantryApplication.Models.Pantry", "Pantry")
                        .WithMany()
                        .HasForeignKey("PantryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pantry");
                });
#pragma warning restore 612, 618
        }
    }
}
